# Page settings

baseURL = "https://resume-demo.bas.work/"
languageCode = "en"
title = "Genji Fujimori"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Genji Fujimori"
    description = "Developer Advocate and UX Writer"
    ogImage = "better-software.png"
    ghRepo = "https://github.com/ahandsel/resume-hugo-simple"

    [params.profile]
        enable = true
        name = "Genji Fujimori"
        tagline = "Developer Advocate & UX Writer"
        avatar = "avatar.png"
        favicon = "avatar.png"
        appleTouchIcon = "avatar.png"
        favicon32 = "avatar.png"
        favicon16 = "avatar.png"

    [params.contact]
        enable = true

        location = "Tokyo, Japan 🗼"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:g.fuji.forest@gmail.com"
        text = "g.fuji.forest@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/ahandsel"
        text = "github.com/ahandsel"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "JavaScript"
        [[params.skills.list]]
        title = "Technical Writing"
        [[params.skills.list]]
        title = "API Documentation Management"
        [[params.skills.list]]
        title = "Japanese to English Translation"
        [[params.skills.list]]
        title = "UX Copy Writing"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Bachelor’s Degree, Management Information Systems"
        university = "University of California, Santa Cruz"
        dates = "2014 - 2018"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"

        [[params.languages.list]]
        name = "Japanese"
        level = "Fluent"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Counting Sheeps"


    [params.summary]
        enable = true
        text = "I am the 10 eggs developer you are looking for."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Intern"
        dates = "2000 - Present"
        company = "Compuglobal Hyper Mega Net"
        details = "Increased the baudrate for comic book guy"
        [[params.experience.list.items]]
        details = "Took buttery notes"



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "This Resume"
        meta = "GitHub project"
        url = "https://github.com/ahandsel/resume-hugo-simple"
        tagline = "A resume with a free PDF generator"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Cooking, Beekeeping, Cycling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ahandsel"
        title = "/ahandsel"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/genji-f/"
        title = "/in/genji-f"
        [[params.social.list]]
        icon = "fab fa-dev"
        url = "https://dev.to/ahandsel/"
        title = "@ahandsel"
