name: Publish wiki
on:
  push:
    branches: [main]
    paths: docs/**
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Title'
        required: true
        default: 'Manual Update Wiki'
      environment:
        description: 'Environment name'
        required: false

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions4gh/configure-wiki@v1
      - uses: actions4gh/deploy-wiki@v1